Replace MITRE in project statement "maintainers" section and package.json
standardhealth/vscode-language-fsh pull request #89
Opened 2024-09-09 15:33 UTC by mint-thompson

Indicate that project is maintained by the HL7 community. This also applies to the "description" and "author" fields in `package.json`.

2024-09-09 16:18 UTC, cmoesel requested changes
I've suggested a few small tweaks.

Also, can you add a `# LICENSE` section to the README like we have in many of the other repositories? It should include a copyright statement as well. We want to make it very clear that the copyright was transferred.

2024-09-09 16:18 UTC, cmoesel commented on package.json
> +  "description": "FHIR Shorthand (FSH) Language Support by HL7 community",
I think we can/should just say HL7 here:
```suggestion
  "description": "FHIR Shorthand (FSH) Language Support by HL7",
```

2024-09-09 16:18 UTC, cmoesel commented on package.json
> +  "author": "HL7 community",
Here I'd also just refer to HL7 as the author:
```suggestion
  "author": "Health Level Seven International",
```

2024-09-12 14:57 UTC, cmoesel approved these changes
Looks good to me. Thank you!

2024-09-12 15:44 UTC, jafeltra approved these changes

2024-09-12 17:53 UTC, merged